### ISSUE TITLE
Backend xmpp.js not supported

### ISSUE THREAD

**Issue by sim0nx** [matrix-org/matrix-bifrost#110]
Hi,
I am trying to run the bridge using the stable docker build from yesterday (https://hub.docker.com/layers/matrixdotorg/matrix-bifrost/stable/images/sha256-774db81e7c2e9b68d81a635684556e915b2d664e797da46f881dd372cd4b08a0?context=explore). I followed the readme for setting up the config.yaml and registration.yaml, and I want to use xmpp.js.

When starting the docker container I get:
```
Starting matrix-bifrost ... done
Attaching to matrix-bifrost
matrix-bifrost | Feb-13 15:47:55.320 INFO cli Loading config file %s /data/config.yaml
matrix-bifrost | Feb-13 15:47:55.348 INFO Program Starting purple bridge on port 9555
matrix-bifrost | (node:1) UnhandledPromiseRejectionWarning: Error: Backend xmpp.js not supported
matrix-bifrost |     at Program.runBridge (/app/src/Program.ts:186:19)
matrix-bifrost |     at runNextTicks (internal/process/task_queues.js:59:5)
matrix-bifrost |     at processImmediate (internal/timers.js:412:9)
matrix-bifrost | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
matrix-bifrost | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Snippets from the config file:
```
purple:
  # For selecting a specific backend. One of "node-purple", "xmpp.js". Defaults to "node-purple"
  backend: "xmpp.js"
```

Any help would be appreciated.

**Comment by Half-Shot** [comment]
Yeah it's a documentation mistake, should be `xmpp-js`.

**Comment by sim0nx** [comment]
That did the trick! Thank you :-)
