### ISSUE TITLE
bifrost lost connection to prosody, got an error, didn't reconnect

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/matrix-bifrost#114]
```
Mar  2 13:15:38 docker-bifrost[768]: Mar-2 13:15:38.872 ERROR XMPP-conn StreamError: not-well-formed
Mar  2 13:15:38 docker-bifrost[768]:     at Function.fromElement (/app/node_modules/@xmpp/error/index.js:26:19)
Mar  2 13:15:38 docker-bifrost[768]:     at Component._onElement (/app/node_modules/@xmpp/connection/index.js:118:36)
Mar  2 13:15:38 docker-bifrost[768]:     at Parser.listeners.element (/app/node_modules/@xmpp/connection/index.js:128:12)
Mar  2 13:15:38 docker-bifrost[768]:     at Parser.emit (events.js:223:5)
Mar  2 13:15:38 docker-bifrost[768]:     at Parser.onEndElement (/app/node_modules/@xmpp/xml/lib/Parser.js:60:12)
Mar  2 13:15:38 docker-bifrost[768]:     at SaxLtx.emit (events.js:223:5)
Mar  2 13:15:38 docker-bifrost[768]:     at SaxLtx._handleTagOpening (/app/node_modules/ltx/lib/parsers/ltx.js:40:12)
Mar  2 13:15:38 docker-bifrost[768]:     at SaxLtx.write (/app/node_modules/ltx/lib/parsers/ltx.js:159:18)
Mar  2 13:15:38 docker-bifrost[768]:     at Parser.write (/app/node_modules/@xmpp/xml/lib/Parser.js:78:17)
Mar  2 13:15:38 docker-bifrost[768]:     at Component._onData (/app/node_modules/@xmpp/connection/index.js:69:25)
Mar  2 13:15:38 docker-bifrost[768]:     at Socket.listeners.data (/app/node_modules/@xmpp/connection/index.js:85:12)
Mar  2 13:15:38 docker-bifrost[768]:     at Socket.emit (events.js:223:5)
Mar  2 13:15:38 docker-bifrost[768]:     at addChunk (_stream_readable.js:309:12)
Mar  2 13:15:38 docker-bifrost[768]:     at readableAddChunk (_stream_readable.js:290:11)
Mar  2 13:15:38 docker-bifrost[768]:     at Socket.Readable.push (_stream_readable.js:224:10)
Mar  2 13:15:38 docker-bifrost[768]:     at TCP.onStreamRead (internal/stream_base_commons.js:181:23) {
Mar  2 13:15:38 docker-bifrost[768]:   name: 'StreamError',
Mar  2 13:15:38 docker-bifrost[768]:   condition: 'not-well-formed',
Mar  2 13:15:38 docker-bifrost[768]:   text: '',
Mar  2 13:15:38 docker-bifrost[768]:   application: undefined,
Mar  2 13:15:38 docker-bifrost[768]:   element: Element {
Mar  2 13:15:38 docker-bifrost[768]:     name: 'stream:error',
Mar  2 13:15:38 docker-bifrost[768]:     parent: null,
Mar  2 13:15:38 docker-bifrost[768]:     children: [ [Element] ],
Mar  2 13:15:38 docker-bifrost[768]:     attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' }
Mar  2 13:15:38 docker-bifrost[768]:   }
Mar  2 13:15:38 docker-bifrost[768]: }
Mar  2 13:15:38 docker-bifrost[768]: Mar-2 13:15:38.872 DEBUG XMPP-conn status: closing
Mar  2 13:15:38 docker-bifrost[768]: Mar-2 13:15:38.872 DEBUG XMPP-conn status: close
Mar  2 13:15:38 docker-bifrost[768]: Mar-2 13:15:38.872 DEBUG XMPP-conn status: disconnecting
Mar  2 13:15:38 docker-bifrost[768]: Mar-2 13:15:38.873 ERROR XmppJsInstance Connection to XMPP server was lost..
Mar  2 13:15:38 docker-bifrost[768]: Mar-2 13:15:38.873 DEBUG XMPP-conn status: disconnect
```

After this failure we should probably attempt to reconnect, which we seem to do, but we somehow fail to successfully reconnect - we see repeated attempts for the prosody connection, but no successful ones until we restart the bifrost bridge entirely.

**Comment by mtippmann** [comment]
I can confirm the issue with 28bdaca
