### ISSUE TITLE
"UnhandledPromiseRejectionWarning: Error: Field names cannot contain a ." with NeDB engine

### ISSUE THREAD

**Issue by bodqhrohro** [matrix-org/matrix-bifrost#200]
**Describe the bug**
```
(node:3488955) UnhandledPromiseRejectionWarning: Error: Field names cannot contain a .
    at checkKey (/media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:36:11)
    at /media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:54:7
    at Array.forEach (<anonymous>)
    at checkObject (/media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:53:22)
    at /media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:55:7
    at Array.forEach (<anonymous>)
    at checkObject (/media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:53:22)
    at /media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:55:7
    at Array.forEach (<anonymous>)
    at checkObject (/media/d/temp/git/matrix-bifrost/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/model.js:53:22)
```

**To Reproduce**
IDK :C

**Expected behavior**
Probably those dots should be escaped.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11
 - Version 0.2.0

**Comment by jaller94** [comment]
Try to use PostreSQL, as we're slowly moving away from NeDB.
