### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by robertfoss** [matrix-org/matrix-bifrost#21]
Commit: `054526dacd2dfcea47a07dda1971b7fbb45e00ed`

I'm having some issues with downloading dependencies during `npm install`:
The `https://half-shot.uk/files/node/node-purple/module-v0.0.2-node-v57-linux-x64.tar.gz` url returns a 404, however currently v64 of this file seems to exists.

```
# npm install

> node-purple@0.0.2 install /root/matrix-appservice-purple/node_modules/node-purple
> npm run download && node-pre-gyp install --fallback-to-build --debug


> node-purple@0.0.2 download /root/matrix-appservice-purple/node_modules/node-purple
> deps/download.sh

This IS a supported architecture
Downloading purple headers
--2018-12-29 14:18:50--  https://vorboss.dl.sourceforge.net/project/pidgin/Pidgin/2.13.0/pidgin-2.13.0.tar.bz2
Resolving vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)... 5.10.152.194
Connecting to vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)|5.10.152.194|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8994457 (8.6M) [application/octet-stream]
Saving to: ‘purple.tar.bz2’

purple.tar.bz2                                                                                           100%[==============================================================================================================================================================

2018-12-29 14:18:52 (4.49 MB/s) - ‘purple.tar.bz2’ saved [8994457/8994457]

Downloading purple libraries
--2018-12-29 14:18:52--  https://half-shot.uk/files/libpurple/libpurple-2.13.0-x86_64.tar.xz
Resolving half-shot.uk (half-shot.uk)... 81.153.208.152
Connecting to half-shot.uk (half-shot.uk)|81.153.208.152|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4138480 (3.9M) [application/octet-stream]
Saving to: ‘libpurple.tar.xz’

libpurple.tar.xz                                                                                         100%[==============================================================================================================================================================

2018-12-29 14:18:54 (1.96 MB/s) - ‘libpurple.tar.xz’ saved [4138480/4138480]

Checking checksums, expected values below:
2747150c6f711146bddd333c496870bfd55058bab22ffb7e4eb784018ec46d8f  purple.tar.bz2
e32116caa44a71f78f2382cc414a498b7574b2b614f632fe752ac653af0d959b  libpurple.tar.xz
purple.tar.bz2: OK
libpurple.tar.xz: OK
Extracting files
Removing archives
Finished downloading
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://half-shot.uk/files/node/node-purple/module-v0.0.2-node-v57-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-purple@0.0.2 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs purple' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/share/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--debug" "--module=/root/matrix-appservice-purple/node_modules/node-purple/lib/binding/module.node" "--module_name=module" "--module_path=/root/m
ode-v57"
gyp ERR! cwd /root/matrix-appservice-purple/node_modules/node-purple
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
```

**Comment by robertfoss** [comment]
Updating npm and node to the latest seems to solve this issue.

**Comment by Half-Shot** [comment]
Yep, I need to publish binarys for older versions of node.

**Comment by jaller94** [comment]
Hi Robert,
`package.json` now references node-purple.
