### ISSUE TITLE
Failed to fetch VCard TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-bifrost#235]
```
Feb 27 06:38:13 lethe docker-bifrost[15504]: Feb-27 06:38:12.882 WARN XmppJsGateway Failed to fetch VCard TypeError: Cannot read property 'write' of null
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at /app/node_modules/@xmpp/component-core/node_modules/@xmpp/connection/index.js:338:19
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at new Promise (<anonymous>)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at Component.write (/app/node_modules/@xmpp/component-core/node_modules/@xmpp/connection/index.js:329:12)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at XmppJsInstance.xmppSend (/app/src/xmppjs/XJSInstance.ts:145:27)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at XmppJsInstance.getVCard (/app/src/xmppjs/XJSInstance.ts:442:20)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at XmppJsGateway.getUserInfo (/app/src/xmppjs/XJSGateway.ts:545:41)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at ProfileSync.updateProfile (/app/src/ProfileSync.ts:50:45)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at runMicrotasks (<anonymous>)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Feb 27 06:38:13 lethe docker-bifrost[15504]:     at GatewayHandler.handleRoomJoin (/app/src/GatewayHandler.ts:194:17)
Feb 27 06:38:13 lethe docker-bifrost[15504]: Feb-27 06:38:12.882 DEBUG ProfileSync getUserInfo got: {
Feb 27 06:38:13 lethe docker-bifrost[15504]:   Nickname: 'fooo',
Feb 27 06:38:13 lethe docker-bifrost[15504]:   Avatar: undefined,
Feb 27 06:38:13 lethe docker-bifrost[15504]:   eventName: 'meh',
Feb 27 06:38:13 lethe docker-bifrost[15504]:   who: 'fooo',
Feb 27 06:38:13 lethe docker-bifrost[15504]:   account: { protocol_id: '', username: '' }
Feb 27 06:38:13 lethe docker-bifrost[15504]: }
```

**Comment by Half-Shot** [comment]
This is a symptom of the server closing.
