### ISSUE TITLE
Postgres backend broken

### ISSUE THREAD

**Issue by nikp123** [matrix-org/matrix-bifrost#276]
**Describe the bug**
When setting the database backend to postgres, bifrost will fail to launch.

**To Reproduce**
1. Open ``config.yaml``
2. Change database type to "postgres"
3. Change the database connectionString to the format specified in the default sample config file
4. Launch bifrost
5. Bifrost launches, but the following error message prevents it from progressing further:
```
Aug-9 06:52:16.435 ERROR Program Homeserver cannot reach the bridge. You probably need to adjust your configuration. error: column "matrixuser" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 110,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '33',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3514',
  routine: 'errorMissingColumn'
}
```

**Expected behavior**
That the thing actually works and doesnt act frozen

**Desktop (please complete the following information):**
 - Irrelevant

**Smartphone (please complete the following information):**
 - Irrelevant

**Additional context**
Using the latest Dockerfile self-build of matrix-bifrost

Also, note: I've tried manually dropping and recreating the database a few times to no avail.

**Comment by Half-Shot** [comment]
This is now fixed in latest `develop`.
